language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t shekhar777/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true shekhar777/docker-react npm run test  -- --coverage